# Generated by Django 6.0.7 on 2026-07-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cierredia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='uso',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Gasto', 'Gasto')], default='Venta', max_length=10),
        ),
    ]
