# Generated by Django 6.0.7 on 2026-07-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_perfiles_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='moneda',
            field=models.CharField(choices=[('USD', 'USD'), ('CRC', 'CRC')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
