# Generated by Django 6.0.7 on 2026-07-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_movimiento_moneda_movimiento_tipo_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_cambio',
        ),
    ]
