# Generated by Django 6.0.7 on 2026-07-19 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areareserva',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name='areareserva',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
